language: php

php:
  - 7.4
  - 8.0

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require fxp/composer-asset-plugin:^1.0.0
  - travis_retry composer update --dev --prefer-dist --no-interaction
script:
  - |
    php -S localhost:8080 -t web > /dev/null 2>&1 &
    vendor/bin/codecept run